languageCode = "en-us"
defaultContentLanguage = "en"
# baseURL = "https://shahidshah.netlify.com"
title = "Shahid N. Shah"
# theme = "beautifulhugo"
[params]
  brand = "Medigy"
  GraphQLUrl = "https://devl.dss.next.medigy.com/graphql"
  socialshare = "https://www.medigy.com"
  GoogleCaptchaSite = "6LfB7pMUAAAAAGPYb3zz2z-mwZHjfJkumOnmXvNl"
  GTMCode = "GTM-MRP79T4"
  OWLApiUrl = "https://devl.service.ontology.attest.cloud/"
  siteUrl = "https://devl.next.medigy.com/"
  elasticSearchUrl = "https://prod-es.medigy.com/"
  issoUrl = "https://isso.medigy.com/"
  raUrl = "https://devl.ra.admin.next.medigy.com/"
  gitlabUrl = "https://devl.gl.next.infra.medigy.com/api/v4"
  sitename = "Shahid Shah"
  custom_css = ["css/style.css"]
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML","Calendar", "JSON"]
  events = ["HTML","Calendar"]
  section = ["HTML","JSON"]
[outputFormats.Calendar]
  protocol = "https://"
[taxonomies]
  tag = "tags"
  topics = "categories"
  languages = "languages"
  feedsource = "feedsource"
  tenantid = "tenantId"
  recognitions = "recognitions"
  collections = "collections"
  equalentCollections = "equalentCollections"
  geographyCensusDivisions = "geographyCensusDivisions"
  geographyCensusRegions = "geographyCensusRegions"
  geographyStates = "geographyStates"
  geographyZipCodes = "geographyZipCodes"
  hdoTypes = "hdoTypes"
  institutionTypes = "institutionTypes"
[permalinks]
  news = "/news/:year/:month/:day/:slug/"
  events = "/event/:year/:month/:day/:slug/"
  categories = "/topic/:slug/"
  recognitions = "/recognition/award/:slug/"
  collections = "/topic/:slug/"
[sitemap]
  changefreq = "daily"
  priority = 1.0
  filename = "sitemap.xml"
[markup]
  defaultMarkdownHandler = "goldmark"
[markup.goldmark]
 [markup.goldmark.renderer]
   unsafe = true
